services:
  - type: web
    name: linkedin-api
    env: python
    buildCommand: pip install -r server/requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        sync: false
    buildFilter:
      paths:
        - server/**
    plan: free
    rootDir: server
